"""add new roles, permissions, manager assignments, lead columns

Revision ID: 41d593cdfc47
Revises: e123a7cff666
Create Date: 2026-08-23 10:15:28.292333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41d593cdfc47'
down_revision: Union[str, Sequence[str], None] = 'e123a7cff666'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('can_upload_leads', sa.Boolean(), nullable=True),
    sa.Column('can_start_campaign', sa.Boolean(), nullable=True),
    sa.Column('can_view_transcripts', sa.Boolean(), nullable=True),
    sa.Column('can_manage_analysts', sa.Boolean(), nullable=True),
    sa.Column('can_export_data', sa.Boolean(), nullable=True),
    sa.Column('granted_by', sa.Integer(), nullable=False),
    sa.Column('granted_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_permissions_id'), 'client_permissions', ['id'], unique=False)
    op.create_table('manager_client_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manager_client_assignments_id'), 'manager_client_assignments', ['id'], unique=False)
    op.add_column('leads', sa.Column('assigned_to', sa.Integer(), nullable=True))
    op.add_column('leads', sa.Column('uploaded_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'leads', 'users', ['uploaded_by'], ['id'])
    op.create_foreign_key(None, 'leads', 'users', ['assigned_to'], ['id'])
    op.add_column('users', sa.Column('otp_secret', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('otp_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'otp_verified')
    op.drop_column('users', 'otp_secret')
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_column('leads', 'uploaded_by')
    op.drop_column('leads', 'assigned_to')
    op.drop_index(op.f('ix_manager_client_assignments_id'), table_name='manager_client_assignments')
    op.drop_table('manager_client_assignments')
    op.drop_index(op.f('ix_client_permissions_id'), table_name='client_permissions')
    op.drop_table('client_permissions')
    # ### end Alembic commands ###
